# Generated by Django 3.2.16 on 2022-12-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=25)),
                ('imgsrc', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SomeKeys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_value', models.IntegerField(default=0)),
                ('name', models.TextField(default='')),
            ],
        ),
    ]
